"""creating categories table

Revision ID: 247ad262992a
Revises: 5c58ea432840
Create Date: 2025-12-13 13:30:19.082473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '247ad262992a'
down_revision: Union[str, Sequence[str], None] = '5c58ea432840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_description'), 'categories', ['category_description'], unique=False)
    op.create_index(op.f('ix_categories_category_title'), 'categories', ['category_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_category_title'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_description'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
