"""creating the products table

Revision ID: c09a6268d927
Revises: 
Create Date: 2025-12-12 09:40:28.842647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c09a6268d927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_category'), 'products', ['product_category'], unique=False)
    op.create_index(op.f('ix_products_product_description'), 'products', ['product_description'], unique=False)
    op.create_index(op.f('ix_products_product_price'), 'products', ['product_price'], unique=False)
    op.create_index(op.f('ix_products_product_title'), 'products', ['product_title'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_products_product_title'), table_name='products')
    op.drop_index(op.f('ix_products_product_price'), table_name='products')
    op.drop_index(op.f('ix_products_product_description'), table_name='products')
    op.drop_index(op.f('ix_products_product_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
